### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by roshan-tek** [nyby/meteor-react-js#1]
**Describe the bug**
I get complie Failure while importing Meteor
**To Reproduce**
1. install the meteor-react 
2. import Meteor in App.js 
import Meteor from 'meteor-react-js'; 

**Expected behavior**
shouldn't fail complie

**Error**
./node_modules/meteor-react-js/src/Meteor.js
Module parse failed: Unexpected token (102:6)
You may need an appropriate loader to handle this file type.
|       endpoint,
|       SocketConstructor: WebSocket,
|       ...options,
|     });
|

**Comment by jkthinksmart** [comment]
@roshan-tek which version are you using? This doesn't seem to be a bug related to the library, but rather to your build configuration.

**Comment by roshan-tek** [comment]
@jkthinksmart 
I am using the latest version
 "meteor-react-js": "^1.1.21" with 
  "react": "^16.14.0",

**Comment by xwz** [comment]
There are some missing configurations, we should strive for the package to work with basic react setup. E.g. the following should work 

~~~
npx create-react-app my-app
cd my-app
npm install --save meteor-react-js
npm start
~~~

**Comment by roshan-tek** [comment]
@xwz 
Thanks for the reply.
I tried with the fresh react app. i get another issue now;
./node_modules/meteor-react-js/src/user/Accounts.js 12:16
Module parse failed: Unexpected token (12:16)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| class AccountsPassword {
>   _hashPassword = hashPassword;
|   createUser = (options, callback = () => {}) => {
|     // Replace password with the hashed password.

**Comment by xwz** [comment]
The default create-react-app doesn't have many options for configuring the babel, but it does have a typescript template that should work.
~~~
npx create-react-app my-app --template typescript
cd my-app
npm install --save meteor-react-js
~~~

**Comment by roshan-tek** [comment]
I don't have any idea about typescript, though I tried to do so but I get ;
Could not find a declaration file for module 'meteor-react-js'. 'D:/geniee-react/node_modules/meteor-react-js/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/meteor-react-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'meteor-react-js';`

And when I try to install 

 E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fmeteor-react-js - Not found

**Comment by xwz** [comment]
OK, the latest package 1.1.24 should work with normal js, no need for typescript. just 

`npm install --save meteor-react-js`

**Comment by roshan-tek** [comment]
@xwz  Thanks,
Version 1.1.24 works now.
